### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [dkniffin/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license or a screen shot.

Please add a screen shot so people can see what the theme will look like without having to install it.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

**Comment by dkniffin** [comment]
done.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/693
